work with dojo
asv-duylk/django-gae pull request #12
Opened 2017-05-22 02:15 UTC by asv-duylk

2017-05-23 09:42 UTC, asv-thanglna commented on static/js/widget/App.js
> +					handleAs: "json"
truyền biến limit cho apis. chỉ lấy 5 greetings thôi.
module nao ko dùng thì remove.

2017-05-23 09:43 UTC, asv-thanglna commented on static/js/widget/GreetingWidget.js
> +
remove những line trống

2017-05-23 09:44 UTC, asv-thanglna commented on static/js/widget/GreetingWidget.js
> +					on(domNode, mouse.enter, lang.hitch(this, "_changeBackground", this.mouseBackgroundColor)),
dùng hover của css.

2017-05-23 09:44 UTC, asv-thanglna commented on static/js/widget/GreetingWidget.js
> +			domStyle.set(this.informationNode, "display", "block");
sao ko gọi hàm này _showAndHideEditContent() ???

2017-05-23 09:46 UTC, asv-thanglna commented on static/js/widget/css/GreetingWidget.css
> +.greetingWidget {
sửa lại coding style.

2017-05-23 09:47 UTC, asv-thanglna commented on templates/guestbook/index_page.html
> -			// these HTTP methods do not require CSRF protection
code não ko dùng nữa thì remove đi.

2017-05-24 01:40 UTC, vn-trinhtk requested changes

2017-05-24 01:40 UTC, asv-trinhtk commented on static/js/widget/App.js
> +	"dojo/dom",
sort thứ tự import theo bảng chữ cái và độ ưu tiên sau:
- _base
- dojo
- dijit 
- dojox
- template
- nls 
- read-only

2017-05-24 01:40 UTC, asv-trinhtk commented on static/js/widget/App.js
> +				xhr.get("api/v1/default_guestbook/greetings/", {
App nên là 1 class chứa 1 `GreetingContainer`, load greeting chỉ nên là 1 phương thức trong class `GreetingContainer`

2017-05-24 01:40 UTC, asv-trinhtk commented on static/js/widget/App.js
> +					var greetingContainer = dom.byId("greetingContainer");
dùng attach-point

2017-05-24 01:40 UTC, asv-trinhtk commented on static/js/widget/GreetingWidget.js
> +	"dojo/text!./templates/GreetingWidget.html"
sort thứ tự module lại

2017-05-24 01:40 UTC, asv-trinhtk commented on static/js/widget/GreetingWidget.js
> +		avatarEdit: require.toUrl("../static/images/edit.png"),
hình để trong template đc mà ?!

2017-05-24 01:40 UTC, asv-trinhtk commented on static/js/widget/GreetingWidget.js
> +			this._showAndHideEditContent(true);
xem lại cách đặt tên hàm

2017-05-24 01:40 UTC, asv-trinhtk commented on static/js/widget/GreetingWidget.js
> +					on(this.avatarEditNode, "click", lang.hitch(this, "_clickEdit")),
mở google, tra chữ `avatar` là gì, xem xem có cần đặt tên dài như vậy k ?

2017-05-24 01:40 UTC, asv-trinhtk commented on static/js/widget/GreetingWidget.js
> +			this._showAndHideEditContent(false);
nếu edit chỉ làm thao tác này, tại sao ko đưa hẳn vào trong `on(this.editNode, 'click',....)`

2017-05-24 01:40 UTC, asv-trinhtk commented on static/js/widget/GreetingWidget.js
> +			var content = this.editContentNode.value;
cách khai báo biến:
```
var a = xx,
    b = c,
    d = z;
```

2017-05-24 01:40 UTC, asv-trinhtk commented on static/js/widget/GreetingWidget.js
> +				alert("Update failed.")
alert failed + error trả về từ server

2017-05-24 01:40 UTC, asv-trinhtk commented on static/js/widget/GreetingWidget.js
> +		_showAndHideEditContent: function (value) {
chú ý cách đặt tên hàm cho dễ hiểu:
`_showAndHideEditContent` => `toggleEdit`

2017-05-24 01:40 UTC, asv-trinhtk commented on static/js/widget/GreetingWidget.js
> +		_showAndHideEditContent: function (value) {
ko truyền cờ như vậy, khó hiểu lắm.
Tạo 1 biến:  _isEditing, khi mở ra thì bật thành True, click lần nữa thì close & update lại biến đó trong hàm này

2017-05-24 01:40 UTC, asv-trinhtk commented on static/js/widget/GreetingWidget.js
> +					alert("Deleted failed.")
+ lỗi từ server

2017-05-24 01:40 UTC, asv-trinhtk commented on static/js/widget/GreetingWidget.js
> +				this.avatarEditNode.src = imagePath;
ko cần hàm này

2017-05-24 01:40 UTC, asv-trinhtk commented on static/js/widget/GreetingWidget.js
> +			}
ko cần hàm này

2017-05-24 01:40 UTC, asv-trinhtk commented on templates/guestbook/index_page.html
> +				cookie("csrf_token", "{{ csrf_token }}");
để trong config

2017-05-24 01:40 UTC, asv-trinhtk commented on templates/guestbook/index_page.html
> +	require(["dojo/cookie",
sửa lại coding style

2017-05-29 01:52 UTC, vn-trinhtk requested changes

2017-05-29 01:52 UTC, asv-trinhtk commented on static/js/widget/App.js
> +			this.loadGreeting();
```
startup: function() {
	this.inherited(arguments);
	this.loadGreeting();
}
```

2017-05-29 01:52 UTC, asv-trinhtk commented on static/js/widget/GreetingWidget.js
> + * Created by newmember on 17/05/2017.
ko để lại sign trong source

2017-05-30 05:44 UTC, merged